### ISSUE TITLE
Error at library inizialization

### ISSUE THREAD

**Issue by SegantiniAlice** [ScrollPrize/vesuvius#7]
Hi, 
I've installed the library but could not use it, since importing the library in an empty script resulted in an Exception with the message 
"Could not update the remote file paths."
 I tracked down the issue and solved it by adding a simple check on the length of a variable in the web scraper in parser.py. I'll open a pull request proposing this solution.
Best regards

**Comment by giorgioangel** [comment]
Thank you!!
